module.exports = [
    {
        makername: 'Bethel Creamery',
        makertype: 'cheese maker',
        city: 'Swan Lake',
        state: 'New York',
        products: 'cheese',
        website: 'https://pellehpoultry.com/about-pelleh-poultry/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'chocolate milk, greek yogurt, unstrained leben',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-74.7820, 41.7531]
    },
    {
        makername: 'Valley Shepherd Creamery',
        city: 'Long Valley',
        state: 'New Jersey',
        makertype: 'cheese maker',
        website: 'http://www.valleyshepherd.com/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'verigot, goat gouda, european style fromage of goat, sheep and cows',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-74.7802, 40.7859]
    },
    {
        makername: 'Bobolink Dairy and Bakehouse',
        city: 'Milford',
        state: 'New Jersey',
        makertype: 'cheese maker',
        website: 'http://www.cowsoutside.com/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'cave aged raw cheddars',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-75.0946, 40.5687]
    },
    {
        makername: 'Fulper Family Farmstead',
        city: 'Lambertville',
        state: 'New Jersey',
        makertype: 'cheese maker',
        website: 'https://fulperfarms.com/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'cheddar and gouda',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-74.9429, 40.3659]
    },
    {
        makername: 'Cherry Grove Farm',
        city: 'Lawrenceville',
        state: 'New Jersey',
        makertype: 'cheese maker',
        website: 'https://www.cherrygrovefarm.com/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'aged cheeses',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-74.7361, 40.3016]
    },
    {
        makername: 'Alba Vineyard',
        city: 'Milford',
        state: 'New Jersey',
        makertype: 'wine maker',
        website: 'https://www.albavineyard.com/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1620262809/winecheeseapp/geyzdkwm9efalxq1wepn.jpg',
        products: 'merlot and sparkling wines',
        filename: 'winecheeseapp/geyzdkwm9efalxq1wepn',
        longLat: [-75.0946, 40.5687]
    },
    {
        makername: '5 Spoke Creamery',
        makertype: 'cheese maker',
        city: 'Goshen',
        state: 'New York',
        products: 'cheese',
        website: 'http://www.5spokecreamery.com/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'gouda, cheddar and goat fromage',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-74.324319, 41.402038]
    },
    {
        makername: 'Mt Townsend Creamery',
        makertype: 'cheese maker',
        city: 'Port Townsend',
        state: 'Washington',
        products: 'cheese',
        website: 'https://mttownsendcreamery.com/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'Soft ripened cheese',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-122.7604, 48.1170]
    },
    {
        makername: 'Beechers Handmade Cheese',
        makertype: 'cheese maker',
        city: 'Seattle',
        state: 'Washington',
        products: 'cheese',
        website: 'beechershandmadecheese.com',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'Cheddar',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-122.3321, 47.6062]
    },
    {
        makername: 'Hawk Haven Vineyard and Winery',
        city: 'Rio Grande',
        state: 'New Jersey',
        makertype: 'wine maker',
        website: 'hawkhavenvineyard.com',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1620262809/winecheeseapp/geyzdkwm9efalxq1wepn.jpg',
        products: 'Pinot Grigio',
        filename: 'winecheeseapp/geyzdkwm9efalxq1wepn',
        longLat: [-74.8816, 39.0146]
    },
    {
        makername: 'Rogue Creamery',
        makertype: 'cheese maker',
        city: 'Central Point',
        state: 'Oregon',
        products: 'cheese, rogue river blue',
        website: 'roguecreamery.com',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1620262259/winecheeseapp/zrtfysetxxvlt75f9qzt.jpg',
        products: 'Cheddar',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-122.6203, 45.3975]
    },
    {
        makername: 'Satori Cheese',
        makertype: 'cheese maker',
        city: 'Plymouth',
        state: 'Wisconsin',
        products: 'cheese',
        website: 'https://www.sartoricheese.com/home.html',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'extra aged asiago',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-87.9770, 43.7486]
    },
    {
        makername: 'Haystack Mountain Creamery',
        makertype: 'cheese maker',
        city: 'Longmont',
        state: 'Colorado',
        products: 'cheese',
        website: 'https://haystackmountaincheese.com/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'Jack and bloomy rind cheeses',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-105.1019, 40.1672]
    },
    {
        makername: 'Pure Luck Dairy',
        makertype: 'cheese maker',
        city: 'Dripping Springs',
        state: 'Texas',
        products: 'cheese',
        website: 'http://www.purelucktexas.com/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'goat chevre, feta, saint maure',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-98.0867, 30.1902]
    },
    {
        makername: 'Blue Heron Farm',
        makertype: 'cheese maker',
        city: 'Field Store',
        state: 'Texas',
        products: 'cheese',
        website: 'blueherontexas.com',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'Jack and bloomy rind cheeses',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-95.9558, 30.1446]
    },
    {
        makername: 'Woodward Canyon',
        city: 'Walla Walla',
        state: 'Washington',
        makertype: 'wine maker',
        website: 'https://www.woodwardcanyon.com/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1620262809/winecheeseapp/geyzdkwm9efalxq1wepn.jpg',
        products: 'cabernet sauvignon, chardonnay, merlot',
        filename: 'winecheeseapp/geyzdkwm9efalxq1wepn',
        longLat: [-118.3430, 46.0646]
    },
    {
        makername: 'Kana Winery',
        city: 'Yakima',
        state: 'Washington',
        makertype: 'wine maker',
        website: 'kanawinery.com',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1620262809/winecheeseapp/geyzdkwm9efalxq1wepn.jpg',
        products: 'chardonnay',
        filename: 'winecheeseapp/geyzdkwm9efalxq1wepn',
        longLat: [-120.5059, 46.6021]
    },
    {
        makername: 'Cowgirl Creamery',
        makertype: 'cheese maker',
        city: 'Point Reyes Station',
        state: 'California',
        products: 'cheese, triple cream mt tam, organic soft ripened cheese',
        website: 'https://cowgirlcreamery.com/',
        submittedBy: 'Madelyn',
        url: 'https://res.cloudinary.com/dceyz9gtp/image/upload/v1622038145/winecheeseapp/mp24fvxknr4yvp2yvqfs.jpg',
        products: 'Jack and bloomy rind cheeses',
        filename: 'winecheeseapp/zrtfysetxxvlt75f9qzt',
        longLat: [-122.8069, 38.0691]
    },
]
    ;